USE library;

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
ID INT NOT NULL PRIMARY KEY,
TITLE VARCHAR(64),
AUTHOR VARCHAR(32),
BOOKYEAR NUMERIC(4),
ISBN NUMERIC(32)
);

select * FROM books;

#GRANT ALL PRIVILEGES ON library.* to user@localhost;

#ALTER USER 'user'@'localhost' IDENTIFIED BY 'admin1';